trigger:
- master

pr: none

pool:
  name: 'ConfigCat Agents'

steps:
  - task: Docker@2
    displayName: build
    inputs:
      containerRegistry: 'Docker Hub'
      repository: configcat/docs
      command: build
      Dockerfile: Dockerfile
      buildContext: '$(System.DefaultWorkingDirectory)'
      arguments: '--build-arg SONAR_TOKEN=$(sonar_token) --network=host $(additional_arguments)'

  - task: Docker@2
    displayName: push
    inputs:
      containerRegistry: 'Docker Hub'
      repository: configcat/docs
      command: push

  - script: |
      mkdir -pv $(build.artifactstagingdirectory)/output
      rm -rf $(build.artifactstagingdirectory)/output/*
      IMAGEID=$(docker images configcat/home-page:$(Build.BuildId) --format "{{.ID}}")
      CONTAINERID=$(docker create $IMAGEID)
      docker cp $CONTAINERID:/usr/share/nginx/temphtml/. $(build.artifactstagingdirectory)/output/
      docker rm $CONTAINERID
    displayName: "Copy files from docker image"
    
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: $(build.artifactstagingdirectory)/output/
      artifact: Docs
