trigger:
- master

pr: none

pool:
  name: 'ConfigCat Agents'

steps:

- task: Docker@2
  displayName: build
  inputs:
    containerRegistry: 'Docker Hub'
    repository: configcat/docs
    command: build
    Dockerfile: Dockerfile
    buildContext: '$(System.DefaultWorkingDirectory)'
    arguments: '--build-arg SONAR_TOKEN=$(sonar_token) --network=host $(additional_arguments)'

- task: Docker@2
  displayName: push
  inputs:
    containerRegistry: 'Docker Hub'
    repository: configcat/docs
    command: push
