trigger:
- master

pr: none

pool:
  name: Contabo

variables:
  ${{ if eq( variables['skip_cache'], 'true' ) }}: 
    buildArguments: '--build-arg SONAR_TOKEN=$(sonar_token) --network=host'
  ${{ else }}: 
    buildArguments: '--build-arg SONAR_TOKEN=$(sonar_token) --network=host --no-cache'

steps:

- task: Docker@2
  displayName: build
  inputs:
    containerRegistry: 'Docker Hub'
    repository: configcat/docs
    command: build
    Dockerfile: Dockerfile
    buildContext: '$(System.DefaultWorkingDirectory)'
    arguments: $(buildArguments)

- task: Docker@2
  displayName: push
  inputs:
    containerRegistry: 'Docker Hub'
    repository: configcat/docs
    command: push
